fix #43 to compile with c++17
key4hep/k4-spack pull request #44
Opened 2020-09-12 16:41 UTC by joequant

2020-09-13 17:01 UTC, vvolkl commented
Thanks @joequant! Can you submit this patch also to the upstream repo: https://github.com/FCALSW/FCalClusterer/ ?

2020-09-14 07:57 UTC, vvolkl requested changes

2020-09-14 07:57 UTC, vvolkl commented on packages/fcalclusterer/package.py
> +    patch("random-shuffle-c17.patch")
From the issue you opened, I gather this has been fixed in master. In that case I'd suggest to do:
```suggestion
    patch("random-shuffle-c17.patch", when="@:1.0.1")
```

2020-09-16 09:09 UTC, andresailer commented
Superseded by #53 ?

2020-09-20 08:13 UTC, vvolkl commented
#53 fixes the issue in `1.0.2`, but this will still be good to merge for `1.0.1`

2020-09-20 08:13 UTC, merged