add compile fix
key4hep/k4-spack pull request #46
Opened 2020-09-12 16:48 UTC by joequant

fixes these errors

/tmp/user/spack-stage/spack-stage-lccontent-3.1.5-s3ww3pfjecbqehfgqgxvydwcvqk466dp/spack-src/include/LCUtility/KDTreeLinkerAlgoT.h:275:22: error: '*' in boolean context, suggest '&&' instead [-Werror=int-in-bool-context]
  275 |             isInside *= thedim >= trackBox.dimmin[i] && thedim <= trackBox.dimmax[i];
      |             ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/user/spack-stage/spack-stage-lccontent-3.1.5-s3ww3pfjecbqehfgqgxvydwcvqk466dp/spack-src/include/LCUtility/KDTreeLinkerAlgoT.h:292:30: error: '*' in boolean context, suggest '&&' instead [-Werror=int-in-bool-context]
  292 |             isFullyContained *= (regionmin >= trackBox.dimmin[i] && regionmax <= trackBox.dimmax[i]);
      |             ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/user/spack-stage/spack-stage-lccontent-3.1.5-s3ww3pfjecbqehfgqgxvydwcvqk466dp/spack-src/include/LCUtility/KDTreeLinkerAlgoT.h:293:29: error: '*' in boolean context, suggest '&&' instead [-Werror=int-in-bool-context]
  293 |             hasIntersection *= (regionmin < trackBox.dimmax[i] && regionmax > trackBox.dimmin[i]);
      |             ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/user/spack-stage/spack-stage-lccontent-3.1.5-s3ww3pfjecbqehfgqgxvydwcvqk466dp/spack-src/include/LCUtility/KDTreeLinkerAlgoT.h:313:30: error: '*' in boolean context, suggest '&&' instead [-Werror=int-in-bool-context]
  313 |             isFullyContained *= (regionmin >= trackBox.dimmin[i] && regionmax <= trackBox.dimmax[i]);
      |             ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/user/spack-stage/spack-stage-lccontent-3.1.5-s3ww3pfjecbqehfgqgxvydwcvqk466dp/spack-src/include/LCUtility/KDTreeLinkerAlgoT.h:314:29: error: '*' in boolean context, suggest '&&' instead [-Werror=int-in-bool-context]
  314 |             hasIntersection *= (regionmin < trackBox.dimmax[i] && regionmax > trackBox.dimmin[i]);
      |             ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

2020-09-13 17:18 UTC, vvolkl commented
It seems like a sensible warning, so I wouldn't like to disable it. Why not do as the compiler suggest and add a patch to change ` var *= x`  to `var = var && x`?

2020-09-14 06:19 UTC, joequant commented
Will try to see if that works, and if it does, will submit patch upstream.

On Mon, Sep 14, 2020 at 1:18 AM vvolkl <notifications@github.com> wrote:

> It seems like a sensible warning, so I wouldn't like to disable it. Why
> not do as the compiler suggest and add a patch to change var *= x to var
> = var && x?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/key4hep/k4-spack/pull/46#issuecomment-691698735>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAWGAGPWACO6B6IN7ANYHKDSFT5H5ANCNFSM4RJW7DQQ>
> .
>

2020-09-14 08:47 UTC, joequant commented
Changed patch to file compile warning

2020-09-14 09:08 UTC, vvolkl commented on packages/lccontent/package.py
> +            args.append('-DCMAKE_CXX_FLAGS=-Wno-int-in-bool-context')
With the patch, this flag is no longer needed.

2020-09-17 10:04 UTC, vvolkl requested changes
Once the compiler flag is removed, this looks good to be merged.

2020-10-21 08:29 UTC, vvolkl commented on packages/lccontent/package.py
> +            args.append('-DCMAKE_CXX_FLAGS=-Wno-int-in-bool-context')
```suggestion

```

2020-10-21 12:40 UTC, vvolkl commented on packages/lccontent/package.py
> +    patch("bool-int.patch")
```suggestion
    patch("bool-int.patch", when="@:3.1.5")
```

2020-10-21 12:41 UTC, merged